from enum import StrEnum


class RunStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class QueueReason(StrEnum):
    INITIAL = "INITIAL"
    RETRY = "RETRY"
    RECOVERY = "RECOVERY"


class ToolEffectType(StrEnum):
    READ = "READ"


class ToolCallStatus(StrEnum):
    CREATED = "CREATED"
    READY = "READY"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    DENIED = "DENIED"
    NOT_EXECUTED = "NOT_EXECUTED"


class ModelInvocationStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class MessageRole(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    TOOL = "TOOL"


class EventType(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    RUN_QUEUED = "RUN_QUEUED"
    RUN_CLAIMED = "RUN_CLAIMED"
    RUN_RECOVERED = "RUN_RECOVERED"
    RUN_STARTED = "RUN_STARTED"
    MODEL_STARTED = "MODEL_STARTED"
    MODEL_COMPLETED = "MODEL_COMPLETED"
    MODEL_FAILED = "MODEL_FAILED"
    TOOL_PROPOSED = "TOOL_PROPOSED"
    TOOL_STARTED = "TOOL_STARTED"
    TOOL_RETRY_READY = "TOOL_RETRY_READY"
    TOOL_DENIED = "TOOL_DENIED"
    TOOL_SUCCEEDED = "TOOL_SUCCEEDED"
    TOOL_FAILED = "TOOL_FAILED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
