from enum import StrEnum


class RunStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_ACTION_RESOLUTION = "WAITING_ACTION_RESOLUTION"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class QueueReason(StrEnum):
    INITIAL = "INITIAL"
    RETRY = "RETRY"
    APPROVAL_RESOLVED = "APPROVAL_RESOLVED"
    ACTION_RESOLVED = "ACTION_RESOLVED"
    RECOVERY = "RECOVERY"
    YIELD = "YIELD"
    RESCHEDULED = "RESCHEDULED"


class ToolEffectType(StrEnum):
    READ = "READ"
    WRITE = "WRITE"
    EXTERNAL_SIDE_EFFECT = "EXTERNAL_SIDE_EFFECT"
    DESTRUCTIVE = "DESTRUCTIVE"


class ReconciliationMode(StrEnum):
    AUTHORITATIVE = "AUTHORITATIVE"
    BEST_EFFORT = "BEST_EFFORT"
    NONE = "NONE"


class ExternalActionStatus(StrEnum):
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    READY = "READY"
    EXECUTING = "EXECUTING"
    UNKNOWN = "UNKNOWN"
    RECONCILING = "RECONCILING"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"


class ToolCallStatus(StrEnum):
    CREATED = "CREATED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    READY = "READY"
    EXECUTING = "EXECUTING"
    UNRESOLVED = "UNRESOLVED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    DENIED = "DENIED"
    NOT_EXECUTED = "NOT_EXECUTED"


class ToolExecutionAttemptStatus(StrEnum):
    STARTED = "STARTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


class ReconciliationAttemptStatus(StrEnum):
    STARTED = "STARTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ReconciliationBusinessResult(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    NOT_EXECUTED = "NOT_EXECUTED"
    UNKNOWN = "UNKNOWN"


class ActionResolutionOutcome(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"


class ModelInvocationStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class MessageRole(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    TOOL = "TOOL"


class EventType(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    RUN_QUEUED = "RUN_QUEUED"
    RUN_CLAIMED = "RUN_CLAIMED"
    RUN_RECOVERED = "RUN_RECOVERED"
    RUN_STARTED = "RUN_STARTED"
    RUN_CANCEL_REQUESTED = "RUN_CANCEL_REQUESTED"
    RUN_CANCELLED = "RUN_CANCELLED"
    MODEL_STARTED = "MODEL_STARTED"
    MODEL_COMPLETED = "MODEL_COMPLETED"
    MODEL_FAILED = "MODEL_FAILED"
    MODEL_RESULT_DISCARDED = "MODEL_RESULT_DISCARDED"
    TOOL_PROPOSED = "TOOL_PROPOSED"
    POLICY_DECIDED = "POLICY_DECIDED"
    ACTION_PREPARED = "ACTION_PREPARED"
    ACTION_COMMITTED = "ACTION_COMMITTED"
    ACTION_SUCCEEDED = "ACTION_SUCCEEDED"
    ACTION_UNKNOWN = "ACTION_UNKNOWN"
    ACTION_FAILED = "ACTION_FAILED"
    ACTION_RETRY_READY = "ACTION_RETRY_READY"
    ACTION_MANUAL_REVIEW = "ACTION_MANUAL_REVIEW"
    ACTION_RESOLUTION_RECORDED = "ACTION_RESOLUTION_RECORDED"
    ACTION_ABORTED = "ACTION_ABORTED"
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
    RECONCILIATION_SUCCEEDED = "RECONCILIATION_SUCCEEDED"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
    RECONCILIATION_RETRY_SCHEDULED = "RECONCILIATION_RETRY_SCHEDULED"
    TOOL_STARTED = "TOOL_STARTED"
    TOOL_RETRY_READY = "TOOL_RETRY_READY"
    TOOL_RETRY_SCHEDULED = "TOOL_RETRY_SCHEDULED"
    TOOL_DENIED = "TOOL_DENIED"
    TOOL_SUCCEEDED = "TOOL_SUCCEEDED"
    TOOL_FAILED = "TOOL_FAILED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
    RUN_YIELDED = "RUN_YIELDED"


class GovernanceMode(StrEnum):
    LEGACY_STAGE32 = "LEGACY_STAGE32"
    GOVERNED = "GOVERNED"


class PrincipalType(StrEnum):
    USER = "USER"
    SERVICE = "SERVICE"


class GovernancePolicyStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    RETIRED = "RETIRED"


class GovernanceDecision(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"


class ApprovalRequestStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    DENIED = "DENIED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
