from enum import StrEnum


class RunStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class QueueReason(StrEnum):
    INITIAL = "INITIAL"
    RETRY = "RETRY"
    APPROVAL_RESOLVED = "APPROVAL_RESOLVED"
    ACTION_RESOLVED = "ACTION_RESOLVED"
    RECOVERY = "RECOVERY"
    YIELD = "YIELD"
    RESCHEDULED = "RESCHEDULED"


class ToolEffectType(StrEnum):
    READ = "READ"
    WRITE = "WRITE"
    EXTERNAL_SIDE_EFFECT = "EXTERNAL_SIDE_EFFECT"
    DESTRUCTIVE = "DESTRUCTIVE"


class ReconciliationMode(StrEnum):
    AUTHORITATIVE = "AUTHORITATIVE"
    BEST_EFFORT = "BEST_EFFORT"
    NONE = "NONE"


class ExternalActionStatus(StrEnum):
    READY = "READY"
    EXECUTING = "EXECUTING"
    UNKNOWN = "UNKNOWN"
    RECONCILING = "RECONCILING"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"


class ToolCallStatus(StrEnum):
    CREATED = "CREATED"
    READY = "READY"
    EXECUTING = "EXECUTING"
    UNRESOLVED = "UNRESOLVED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    DENIED = "DENIED"
    NOT_EXECUTED = "NOT_EXECUTED"


class ToolExecutionAttemptStatus(StrEnum):
    STARTED = "STARTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


class ModelInvocationStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class MessageRole(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    TOOL = "TOOL"


class EventType(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    RUN_QUEUED = "RUN_QUEUED"
    RUN_CLAIMED = "RUN_CLAIMED"
    RUN_RECOVERED = "RUN_RECOVERED"
    RUN_STARTED = "RUN_STARTED"
    MODEL_STARTED = "MODEL_STARTED"
    MODEL_COMPLETED = "MODEL_COMPLETED"
    MODEL_FAILED = "MODEL_FAILED"
    MODEL_RESULT_DISCARDED = "MODEL_RESULT_DISCARDED"
    TOOL_PROPOSED = "TOOL_PROPOSED"
    ACTION_PREPARED = "ACTION_PREPARED"
    ACTION_COMMITTED = "ACTION_COMMITTED"
    ACTION_SUCCEEDED = "ACTION_SUCCEEDED"
    ACTION_UNKNOWN = "ACTION_UNKNOWN"
    ACTION_FAILED = "ACTION_FAILED"
    ACTION_ABORTED = "ACTION_ABORTED"
    TOOL_STARTED = "TOOL_STARTED"
    TOOL_RETRY_READY = "TOOL_RETRY_READY"
    TOOL_RETRY_SCHEDULED = "TOOL_RETRY_SCHEDULED"
    TOOL_DENIED = "TOOL_DENIED"
    TOOL_SUCCEEDED = "TOOL_SUCCEEDED"
    TOOL_FAILED = "TOOL_FAILED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
    RUN_YIELDED = "RUN_YIELDED"
